# Generated by Django 5.0.2 on 2024-02-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='name')),
                ('phone', models.CharField(max_length=30, verbose_name='phone')),
                ('address', models.CharField(max_length=2555, verbose_name='address')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('description', models.TextField(verbose_name='description')),
                ('services', models.TextField(verbose_name='services')),
                ('img', models.ImageField(upload_to='media', verbose_name='img')),
            ],
        ),
    ]
