# Generated by Django 5.0.2 on 2024-02-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
